### ISSUE TITLE
Separate modules

### ISSUE THREAD

**Issue by mattblackdev** [YuriGor/deepdash#11]
Hey @YuriGor nice work! Any chance we could export separate modules? Like lodash has:

```
import _omit from 'lodash/omit'
```

for smaller bundle size on the browser?

**Comment by YuriGor** [comment]
Hi @mattblackdev, thank you!
Yes, I also was impressed by this Lodash feature and want to do the same. 

I had no chance to see how it was implemented yet, If you have any ideas about subj - please share.

- What are the best practices, maybe some useful articles about it? 
- Should we just extract base core and all the methods into separate files?
- Should we maintain two require/import build versions?
- Probably I should just copy this approach from Lodash or there are some special limitations in the Lodash implementation caused by its long history? I saw a lot of disappointed feedback about how it was implemented in Lodash.

Finally, I used  `Webpack` + `lodash-webpack-plugin` + `Babel` + `babel-plugin-lodash` and the results was really impressive.

**Comment by YuriGor** [comment]
I [asked](https://github.com/lodash/lodash/issues/4275) Lodash community for advice.
BTW I'll try to split the lib into es6 modules and build it with [Rollup](https://github.com/rollup/rollup)
All the Lodash dependencies will also be refactored.

**Comment by YuriGor** [comment]
Done in v4, see [installation instructions](http://localhost:3000/#installation)
Btw standalone and es6 module (deepdash-es) versions added.

@mattblackdev could you please test it a bit, I need feedback.
