### ISSUE TITLE
Remove Lodash dependency.

### ISSUE THREAD

**Issue by simlu** [YuriGor/deepdash#59]
Your require syntax seems weird. Is there a reason that lodash is not a peer dependency?

**Comment by YuriGor** [comment]
I support two versions of lib:
 - with a Lodash as an external dependency, explicitly provided by client code
- with a Lodash as internal built in dependency.
I am actually not sure what exactly is a "peer" dependency, will read some docs..

**Comment by YuriGor** [comment]
Well, I read about peer deps, and I think it's not a deepdash case. 
Lodash is heavily used internally, so it's a 'normal' dependency.
Depending on build type:
 - if standalone - then used Lodash methods will be tree shaken and bundled by Rollup 
 - if as a mixin extension - then Lodash instance explicitly given by user will be used instead

I have a dream to replace all the Lodash dependencies in the standalone version by native/self-written alternatives. It's especially desired because of #58
After that, I will be able to switch Lodash from deps to peer deps.

Also, it would be good to support also Underscore.js - it still has some good audience, so maybe folks will appreciate Deepdash too. But in this case, I am not sure if I will need to list both Lodash and Underscore as peer deps, because they are alternatives to each other.

**Comment by YuriGor** [comment]
Well, I had several attempts of doing this, and the heaviest thing I found is the clone / cloneDeep method deepdash depends on in filterDeep.
But these attempts made me to learn the core problem deeper so now I am about of great refactoring of filterDeep.
